#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: clinis

# Short bio or description (displayed in the header)
description: clinis by clinis to clinis

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/11950464?v=3&s=140

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: dinis.areias@gmail.com
  facebook:
  flickr:
  github: clinis
  instagram:
  linkedin:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# ---- !! ---
# !! You don't need to change any of the configuration flags below !!
#

permalink: /blog/:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  style: :compressed

# Use the following plug-ins
plugins:
  # Default GitHub Pages gem plugins
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # Optional GitHub Pages gem plugins
  - jekyll-feed
  #- jekyll-redirect-from
  #- jekyll-seo-tag
  - jekyll-sitemap
  #- jekyll-avatar
  - jemoji
  #- jekyll-mentions
  #- jekyll-include-cache

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Create pages inside _pages directory instead of in the root folder
include:
  - _pages

# Collections
collections:
  projects:
    output: true
